# Generated by Django 3.1.2 on 2020-10-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GANs_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlalgorithm',
            name='file',
        ),
        migrations.AddField(
            model_name='mlalgorithm',
            name='file_location',
            field=models.CharField(default='fsadf', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mlalgorithm',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
