# Generated by Django 3.1.2 on 2020-11-06 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GANs_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='ip_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
