# Generated by Django 3.1.2 on 2020-11-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GANs_App', '0002_auto_20201105_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preset_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/preset')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('times_used', models.IntegerField(default=0, max_length=100)),
            ],
        ),
    ]
