# Generated by Django 3.1.2 on 2020-12-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GANs_App', '0003_preset_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset_images',
            name='times_used',
            field=models.IntegerField(default=0),
        ),
    ]
